[package]
name = "extract-tutorial-code"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2024"
publish = false

[[bin]]
name = "extract-tutorial-code"
path = "src/extract_code.rs"

[dependencies]
pulldown-cmark = "0.13"
