[package]
name = "crowdfunding"
version = "0.0.0"
publish = false
edition = "2024"
authors = ["you"]

[lib]
path = "src/crowdfunding.rs"

[dependencies.multiversx-sc]
version = "0.64.1"

[dev-dependencies.multiversx-sc-scenario]
version = "0.64.1"

[workspace]
members = [
    ".",
    "meta",
]
